create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public;

create type public.order_status as enum (
  'pending',
  'preparing',
  'ready',
  'completed',
  'cancelled'
);

create type public.payment_status as enum (
  'unpaid',
  'pending',
  'authorized',
  'paid',
  'failed',
  'refunded'
);

create type public.payment_method as enum ('cash', 'square', 'stripe');
create type public.payment_provider as enum ('square', 'stripe');
create type public.lifecycle_actor as enum ('customer', 'staff', 'system');

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price_cents integer not null default 0 check (price_cents >= 0),
  price numeric(10, 2) generated always as ((price_cents::numeric) / 100) stored,
  category_id bigint references public.categories(id) on delete set null,
  image_url text,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.modifier_groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_name text,
  min_selections integer not null default 0 check (min_selections >= 0),
  max_selections integer not null default 10 check (max_selections >= min_selections),
  required boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.modifier_options (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.modifier_groups(id) on delete cascade,
  name text not null,
  display_name text,
  price_adjustment_cents integer not null default 0 check (price_adjustment_cents >= 0),
  price_adjustment numeric(10, 2)
    generated always as ((price_adjustment_cents::numeric) / 100) stored,
  available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (group_id, name)
);

create table public.item_modifier_groups (
  item_id bigint not null references public.menu_items(id) on delete cascade,
  group_id bigint not null references public.modifier_groups(id) on delete cascade,
  primary key (item_id, group_id)
);

create table public.orders (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  customer_id uuid not null references auth.users(id) on delete restrict,
  idempotency_key text not null check (char_length(idempotency_key) between 16 and 128),
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  pickup_number integer not null check (pickup_number > 0),
  customer_name text not null,
  email text,
  status public.order_status not null default 'pending',
  subtotal_cents integer not null default 0 check (subtotal_cents >= 0),
  tax_cents integer not null default 0 check (tax_cents >= 0),
  total_cents integer not null default 0 check (total_cents >= 0),
  subtotal numeric(10, 2) generated always as ((subtotal_cents::numeric) / 100) stored,
  tax numeric(10, 2) generated always as ((tax_cents::numeric) / 100) stored,
  total numeric(10, 2) generated always as ((total_cents::numeric) / 100) stored,
  notes text,
  cancellation_reason text,
  cancelled_by text check (cancelled_by in ('customer', 'staff') or cancelled_by is null),
  pickup_reminder_sent boolean not null default false,
  payment_status public.payment_status not null default 'unpaid',
  payment_method public.payment_method not null default 'cash',
  payment_provider public.payment_provider,
  payment_reference text,
  payment_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, idempotency_key)
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_name text not null,
  quantity integer not null default 1 check (quantity between 1 and 100),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  total_price_cents integer not null default 0 check (total_price_cents >= 0),
  unit_price numeric(10, 2) generated always as ((unit_price_cents::numeric) / 100) stored,
  total_price numeric(10, 2) generated always as ((total_price_cents::numeric) / 100) stored,
  special_instructions text,
  created_at timestamptz not null default now()
);

create table public.order_item_modifiers (
  id bigint generated by default as identity primary key,
  order_item_id bigint not null references public.order_items(id) on delete cascade,
  modifier_option_id bigint references public.modifier_options(id) on delete set null,
  modifier_name text not null,
  price_adjustment_cents integer not null default 0 check (price_adjustment_cents >= 0),
  price_adjustment numeric(10, 2)
    generated always as ((price_adjustment_cents::numeric) / 100) stored,
  created_at timestamptz not null default now()
);

create table public.order_lifecycle_events (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  from_status public.order_status,
  to_status public.order_status not null,
  actor_type public.lifecycle_actor not null,
  actor_subject text,
  metadata jsonb,
  created_at timestamptz not null default now()
);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  provider public.payment_provider not null,
  status public.payment_status not null,
  amount_cents integer not null check (amount_cents >= 0),
  external_reference text,
  metadata jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table private.pickup_counters (
  service_date date primary key,
  current_number integer not null check (current_number > 0)
);

create table public.settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.settings (key, value) values
  ('tax_rate', '0.0825'),
  ('kitchen_open', 'true'),
  ('kitchen_closed_message', ''),
  ('announcement_enabled', 'false'),
  ('announcement_text', ''),
  ('popular_item_ids', '[]')
on conflict (key) do nothing;

create index categories_sort_idx on public.categories(sort_order, name);
create index menu_items_category_idx on public.menu_items(category_id, available, sort_order);
create index modifier_options_group_idx on public.modifier_options(group_id, available, sort_order);
create index orders_customer_idx on public.orders(customer_id, created_at desc);
create index orders_status_idx on public.orders(status, created_at);
create index orders_created_idx on public.orders(created_at desc);
create index order_items_order_idx on public.order_items(order_id);
create index order_item_modifiers_item_idx on public.order_item_modifiers(order_item_id);
create index lifecycle_order_idx on public.order_lifecycle_events(order_id, created_at);
create unique index payments_provider_reference_idx
  on public.payments(provider, external_reference)
  where external_reference is not null;

create or replace function private.app_role()
returns text
language sql
stable
set search_path = ''
as $$
  select coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '');
$$;

revoke all on function private.app_role() from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.app_role() to anon, authenticated;

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger menu_items_set_updated_at
before update on public.menu_items
for each row execute function private.set_updated_at();

create trigger orders_set_updated_at
before update on public.orders
for each row execute function private.set_updated_at();

create trigger payments_set_updated_at
before update on public.payments
for each row execute function private.set_updated_at();

create trigger settings_set_updated_at
before update on public.settings
for each row execute function private.set_updated_at();

revoke all on function private.set_updated_at() from public;

create or replace function private.enforce_order_status_transition()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = old.status then
    return new;
  end if;

  if new.status = 'cancelled' and old.status in ('pending', 'preparing', 'ready') then
    return new;
  end if;

  if (old.status = 'pending' and new.status = 'preparing')
    or (old.status = 'preparing' and new.status = 'ready')
    or (old.status = 'ready' and new.status = 'completed') then
    return new;
  end if;

  raise exception 'Illegal order status transition from % to %', old.status, new.status
    using errcode = 'check_violation';
end;
$$;

create trigger orders_enforce_status_transition
before update of status on public.orders
for each row execute function private.enforce_order_status_transition();

revoke all on function private.enforce_order_status_transition() from public;

create or replace function private.broadcast_kitchen_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_table_name = 'settings'
    and coalesce(new.key, old.key) not in ('kitchen_open', 'kitchen_closed_message') then
    return null;
  end if;

  perform realtime.broadcast_changes(
    'kitchen',
    tg_op,
    tg_op,
    tg_table_name,
    tg_table_schema,
    new,
    old
  );
  return null;
end;
$$;

revoke all on function private.broadcast_kitchen_change() from public;

create trigger orders_broadcast_kitchen_change
after insert or update or delete on public.orders
for each row execute function private.broadcast_kitchen_change();

create trigger settings_broadcast_kitchen_change
after insert or update or delete on public.settings
for each row execute function private.broadcast_kitchen_change();

alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.modifier_groups enable row level security;
alter table public.modifier_options enable row level security;
alter table public.item_modifier_groups enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_item_modifiers enable row level security;
alter table public.order_lifecycle_events enable row level security;
alter table public.payments enable row level security;
alter table public.settings enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

grant select on public.categories,
  public.menu_items,
  public.modifier_groups,
  public.modifier_options,
  public.item_modifier_groups
to anon, authenticated;

grant select on public.orders,
  public.order_items,
  public.order_item_modifiers,
  public.order_lifecycle_events
to authenticated;

create policy categories_public_read
on public.categories for select
to anon, authenticated
using (true);

create policy menu_items_public_read
on public.menu_items for select
to anon, authenticated
using (available = true or (select private.app_role()) in ('staff', 'admin'));

create policy modifier_groups_public_read
on public.modifier_groups for select
to anon, authenticated
using (true);

create policy modifier_options_public_read
on public.modifier_options for select
to anon, authenticated
using (available = true or (select private.app_role()) in ('staff', 'admin'));

create policy item_modifier_groups_public_read
on public.item_modifier_groups for select
to anon, authenticated
using (true);

create policy orders_customer_or_staff_read
on public.orders for select
to authenticated
using (
  customer_id = (select auth.uid())
  or (select private.app_role()) in ('staff', 'admin')
);

create policy order_items_customer_or_staff_read
on public.order_items for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where public.orders.id = public.order_items.order_id
      and (
        public.orders.customer_id = (select auth.uid())
        or (select private.app_role()) in ('staff', 'admin')
      )
  )
);

create policy order_item_modifiers_customer_or_staff_read
on public.order_item_modifiers for select
to authenticated
using (
  exists (
    select 1
    from public.order_items
    join public.orders on public.orders.id = public.order_items.order_id
    where public.order_items.id = public.order_item_modifiers.order_item_id
      and (
        public.orders.customer_id = (select auth.uid())
        or (select private.app_role()) in ('staff', 'admin')
      )
  )
);

create policy lifecycle_customer_or_staff_read
on public.order_lifecycle_events for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    where public.orders.id = public.order_lifecycle_events.order_id
      and (
        public.orders.customer_id = (select auth.uid())
        or (select private.app_role()) in ('staff', 'admin')
      )
  )
);

create policy kitchen_staff_receive_broadcasts
on realtime.messages for select
to authenticated
using (
  (select realtime.topic()) = 'kitchen'
  and realtime.messages.extension = 'broadcast'
  and coalesce((select auth.jwt() -> 'app_metadata' ->> 'role'), '') in ('staff', 'admin')
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'menu-images',
  'menu-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
